name: Compile SRS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Sing-box
        run: |
          # Скачиваем свежий бинарник sing-box напрямую с GitHub Releases
          LATEST_URL=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r '.assets[] | select(.name | contains("linux-amd64.tar.gz")) | .browser_download_url')
          curl -sL "$LATEST_URL" -o sing-box.tar.gz
          tar -xzf sing-box.tar.gz --strip-components=1
          chmod +x sing-box

      - name: Convert TXT to JSON and compile SRS
        run: |
          jq -R '.' podkop_domains.txt | jq -s '{version: 1, rules: [{domain_suffix: .}]}' > rules.json
          ./sing-box rule-set compile rules.json -o rules.srs

      - name: Create Release and Upload SRS
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: rules.srs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
